site_name: Yggdrasil Catalog Docs
docs_dir: docs/
copyright: Copyright &copy; Titan Byte Data 2025
site_author: Titan Byte Data
site_url: https://titanbytedata.github.io/yggdrasil-catalog-docs/main/
repo_name: yggdrasil-catalog
repo_url: https://github.com/titanbytedata/yggdrasil-catalog-docs

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  font:
    text: ember
  palette:
    primary: light blue
    accent: deep purple
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  highlightjs: true
  hljs_languages:
    - yaml
    - json

plugins:
  - include-markdown
  - search:
      lang:
        - en
  - awesome-pages

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Flux:
    - flux/index.md
    - Apps:
      - flux/apps/airbyte.md
      - flux/apps/airflow.md
      - flux/apps/cloudnative-pg.md
      - flux/apps/karpenter.md
      - flux/apps/tailscale.md
    - Components:
      - flux/components/ebs-storage-class.md
      - flux/components/namespace.md
