---
blank_issues_enabled: false
contact_links:
  - name: Yggdrasil Catalog Community Support
    url: https://github.com/titanbytedata/yggdrasil-catalog/discussions
    about: Please ask and answer questions here.
